### ISSUE TITLE
linode-cli k8s-alpha create should prevalidate cluster names

### ISSUE THREAD

**Issue by displague** [linode/linode-cli#100]
Using the label: `k8s_test`, for example, will result in a nearly completed cluster and a very late error.

```
module.k8s.linode_instance.k8s_master (remote-exec): name: Invalid value: "k8s_test-master-1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Comment by asauber** [comment]
This has been on my personal to do list for a while. Thanks for codifying it

**Comment by displague** [comment]
Hyphens and dots are valid Linode instance names. This may no longer be a concern.

**Comment by LBGarber** [comment]
Closing this issue as k8s-alpha has been [removed](https://github.com/linode/linode-cli/pull/188) from linode-cli.
