### ISSUE TITLE
Multiple Account

### ISSUE THREAD

**Issue by sentabi** [linode/linode-cli#103]
How to manage multiple account using linode-cli?

I can add multiple account using `linode-cli configure`, but there's no way to run linode-cli using specific account

**Comment by Dorthu** [comment]
This is a planned feature that hasn't been implemented yet.  I'll assign myself and start on this as soon as I can

**Comment by Dorthu** [comment]
@sentabi I'm starting work on this now.  These are my initial thoughts on how it'd work - please let me know what you think.

### Registering Additional Users

The existing `configure` command would be expanded to add additional users to your config, and give the option to make the new user the default user.  User would be determined by the token entered during configuration.

### Executing Commands as User

A new argument, `--as-user`, would be added to the CLI to choose which User is using the CLI.  If the username provided is in the config file, that user's config is used for the command.  If a username is provided and it is not in the config, and error is printed and the program exits.  If this argument is omitted, the default user is used (current behavior).

### Changing Default User

A new command, `set-user`, would be added to the CLI.  It would accept a username as an argument, and that username must be present in the config file.  That user would become the default user for commands.

### Viewing Users

A new command, `show-users`, would be added to the CLI.  This command would accept no arguments, and would print a list of all currently-configured users as well as indicating which one is currently the default user.

### Removing Users

A new command, `remove-user`, would be added to the CLI.  This command would accept a username as an argument, and would remove that user from the config.  If that user was the default user, an error would be returned indicating that the default user cannot be removed (and how to change it or add another user).

**Comment by sentabi** [comment]
@Dorthu  
that's exactly what i'm thinking :)

**Comment by Dorthu** [comment]
@sentabi I have an unofficial build of the CLI from my branch hosted [here](https://cli-builds.alpha.linodeobjects.com/linode_cli-2.0.21-py2.py3-none-any.whl) if you want to give this a try without building it yourself.
