### ISSUE TITLE
The k8s-alpha plugin should not hardcode the Python config section that it uses.

### ISSUE THREAD

**Issue by asauber** [linode/linode-cli#115]
https://github.com/linode/linode-cli/blob/master/linodecli/plugins/k8s-alpha.py#L449
and
https://github.com/linode/linode-cli/blob/master/linodecli/plugins/k8s-alpha.py#L59

assumes that the user is using the `DEFAULT` config section, however, if they've set up users with the CLI, then this section is empty.

We should look for the config section of the current user and use that as the source of these variables.

**Comment by Dorthu** [comment]
This was fixed in 2.1.4, which just shipped 👍
