### ISSUE TITLE
Terraform and Kubectl missing

### ISSUE THREAD

**Issue by volatilemolotov** [linode/linode-cli#118]
Plugin asks for Terraform and kubectl even though both are installed. Using fish shell

**Comment by asauber** [comment]
Hi @volatilemolotov can you try something for me?

Can you save the following as test.py and then run it in the same Python environment and let me know what exception is printed?

```
def dep_installed(command):
    nullf = open(os.devnull, 'w')
    spcall([command], stdout=nullf)
    nullf.close()

dep_installed('terraform')
```

e.g.
`$ python test.py`
`$ python3 test.py`

**Comment by asauber** [comment]
@volatilemolotov updated the MWE with missing imports, sorry about that

**Comment by patthiel** [comment]
Are we good to close this issue? @volatilemolotov , are you able to confirm on your end that @asauber addressed your issue?
