### ISSUE TITLE
No option 'region' in section: 'DEFAULT'

### ISSUE THREAD

**Issue by volatilemolotov** [linode/linode-cli#119]
Using the plugin on bash i get the following error:

`No option 'region' in section: 'DEFAULT'`

Tried to reconfigure the linode-cli but still nothing

**Comment by kodumbeats** [comment]
Looks like https://github.com/linode/linode-cli/issues/115

**Comment by volatilemolotov** [comment]
Yes it is, wasnt obvious to me at the time. Closing
