### ISSUE TITLE
Explain in the docs how to add multiple tags when creating things

### ISSUE THREAD

**Issue by asauber** [linode/linode-cli#122]
You do it like this:

```
asauber@linaret2 ~ $ linode-cli linodes create --tags okay --tags wow --tags great --root_pass 'somethign20343##1'
```

Doesn't appear to be documented anywhere

**Comment by asauber** [comment]
Rather than document this, maybe we should change this arg to use

`nargs='*'`

which has better behavior

**Comment by gsauthof** [comment]
Whatever you do please consider also supporting comma delimited tags, e.g. `--tags tag1,tag2`. Right now this literally generates one tag `tag1,tag2`. I don't think that there is really a use for tags containing a comma, thus, it would make a good delimiter.

**Comment by lgarber-akamai** [comment]
Hey there!

I've put up a [pull request](https://github.com/linode/linode-cli/pull/311) to add documentation for specifying multi-value and nested arguments. I've also created a ticket in our internal tracker to look into implementing alternative methods of specifying lists, although this functionality is not planned to be implemented at the moment.

Let us know if you have any other feedback or suggestions :slightly_smiling_face:
