### ISSUE TITLE
[k8s-alpha] Exit if terraform < 0.11.14+ or terraform >= 0.12.0 for now

### ISSUE THREAD

**Issue by asauber** [linode/linode-cli#131]
The k8s-alpha plugin should exit if `terraform version` is greater than or equal to 0.12.0 or `terraform version` is less than 0.11.14

https://github.com/linode/linode-cli/blob/master/linodecli/plugins/k8s-alpha.py

**Comment by rcsalome** [comment]
I decided to try to implement this. Feedback welcome.

It's not clear if Terraform uses true semantic versioning, but if so. It might be better to use a special library for that.
