### ISSUE TITLE
python2 EOL

### ISSUE THREAD

**Issue by patthiel** [linode/linode-cli#133]
>  Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.

We should work to update the build to rely only on python3. (and there's already issues when attempting to install the CLI with python2 pip)

**Comment by ChihweiLHBird** [comment]
Isn't it already based on Python 3 currently?

**Comment by lgarber-akamai** [comment]
@ChihweiLHBird Thanks for the heads up! 

Python 2 support has been dropped in `5.25.0`, so I'll go ahead and close this issue.
