### ISSUE TITLE
OAUTH scope does not include option for Object Storage

### ISSUE THREAD

**Issue by oucil** [linode/linode-cli#142]
I'm beta testing the Object Storage system and I'm trying to use the CLI to create a bucket, but the CLI is responding that my OAUTH token doesn't have the required scope permissions.

I'm using the following, `linode-cli obj mb some.bucket.name` and am getting the following response....

    Request failed: 401
    lerrorsqwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
    x field x reason                                                   x
    tqqqqqqqnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu
    x       x Your OAuth token is not authorized to use this endpoint. x
    mqqqqqqqvqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj

When I go to the console to generate a new `Personal Access Token`, I'm only given the following options:

- Account
- Domains
- Events
- Images
- IPs
- Linodes
- Longview
- NodeBalancers
- StackScripts
- Volumes

There is no option to enable the object storage endpoint.

Is this an error in the CLI, an issue with the Token manager, or something else?  I'm stuck.

Thanks,
Kevin.

**Comment by oucil** [comment]
It just occurred to me that I did not select any defaults when enabling the CLI the first time, I only included the Key itself.  But I don't see anything in the reference manual that indicates how I would supply the region in the CLI call...

**Comment by oucil** [comment]
Just tried `linode-cli obj mb some.bucket.name --region us-east`, no effect, same response.

**Comment by Dorthu** [comment]
@oucil you can use `--cluster us-east-1` to change the cluster the obj plugin talks to.  I'm looking into the token error now.

**Comment by oucil** [comment]
@Dorthu Thanks for the suggestion, but same result again. I'm guessing the root issue is scope related, and that my region question is just a secondary issue?  Appreciate you looking into it!

**Comment by Dorthu** [comment]
It looks like cloud.linode.com presently lacks the ability to create Personal Access Tokens with Object Storage scopes.  I'm forwarding this along to that time.  In the meantime, a token created with all scopes should work, or if you need a specifically scoped token you can use the CLI itself to generate it:

```bash
linode-cli profile token-create --scopes 'object_storage:*,account:read_only'
```

(you'll need to `linode-cli configure` afterward and provide the new token so that the CLI uses it).

**Comment by oucil** [comment]
@Dorthu That's great, thanks!  As we're only beta testing at the moment the "All" scope isn't an issue, and I wasn't aware I could generate the new profile tokens from the CLI like that, so even better.  Thanks for your help.

**Comment by Dorthu** [comment]
This OAuth Scope has been added as an option in cloud.linode.com as well.  Closing this issue.
