### ISSUE TITLE
cluster creation failing

### ISSUE THREAD

**Issue by treesvalley** [linode/linode-cli#145]
getting following error on cluster creation used following command

linode-cli k8s-alpha create tidb-cluster --node-type g6-dedicated-4 --nodes 1 --master-type g6-standard-2 --region ap-south --ssh-public-key $HOME/.ssh/id_rsa.pub

Error: failed to execute "/root/.k8s-alpha-linode/tidb-cluster/.terraform/modules/k8s/scripts/kubeadm-token.sh": /root/.k8s-alpha-linode/tidb-cluster/.terraform/modules/k8s/scripts/kubeadm-token.sh: line 6: python3: command not found
ssh: Could not resolve hostname : Name or service not known

**Comment by jnschaeffer** [comment]
Thanks for the report, @treesvalley. The script causing the error comes from the [terraform-linode-k8s](https://github.com/linode/terraform-linode-k8s) project, which is what we use to provision clusters. I took a look at the line in the script raising the error you're seeing and it calls `python`, not `python3` ([link](https://github.com/linode/terraform-linode-k8s/blob/master/modules/masters/scripts/local/kubeadm-token.sh#L6)). Do you have `python` aliased to `python3` on the system running this?

**Comment by treesvalley** [comment]
no I will try with that

**Comment by LBGarber** [comment]
Closing this issue due to `terraform-linode-k8s` being in experimental status. Feel free to tag me if this issue is still occurring 🙂
