### ISSUE TITLE
[enhancement/suggestion] Command aliases to match standard *NIX commands

### ISSUE THREAD

**Issue by danieldjewell** [linode/linode-cli#149]
I had a thought/suggestion: As it stands now, the commands in linode-cli are functional but, IMHO, are less than intuitive. For example, *nix admins are completely familiar with using commands like ```ls; cp; rm; mv```. I think it would be more user friendly and intuitive to provide aliases (which seems like a good idea instead of flat out modifying the existing command syntax and disrupting users who already have memorized linode-cli commands). 

In other words, provide "ls" as an alias for "list" (and so on) so that one could run: 

```linode-cli linodes ls```

Additionally, supporting a form of auto-completion similar to what is present on many routers and switches would also be helpful. In other words, one would only need to type enough of a command so as to make it unique: there are two "L" commands - "linodes" and "longview" ... so "li" and "lo" are enough to infer the meaning. (This is similar to routers and switches where something like ```sh ip int br``` is shorthand for ```show ip interfaces brief```.) 

The combination of these two things would make it possible to do, for example: 

```linode-cli li ls``` 

in order to list all linodes. If one then aliases "linode-cli" to something shorter (i.e. ```alias lc='linode-cli'```) ... one could shorten this up to a very nice compact command: ```lc li ls```. 

Just a thought - Docker already utilizes the ls/rm/cp syntax... And I think some of the Azure CLI stuff does too? Not suggesting that just because others do something that makes it the "best" or "right" way...

**Comment by jtara1** [comment]
to summarize:
- make aliases for core commands like: `ls`, `cp`, `rm`, `mv`, etc
- autocomplete (linux, macos, windows)
