### ISSUE TITLE
Attempting to create LKE clusters prints CLI version info instead

### ISSUE THREAD

**Issue by jnschaeffer** [linode/linode-cli#154]
When attempting to create an LKE cluster with `linode-cli lke cluster-create`, the CLI prints version info instead:
```
$ linode-cli lke cluster-create --label helloworld --version 1.16
linode-cli 2.10.3
Built off spec version 4.9.0
```

It looks like this is because `--version` is specified as a top-level argument, and the CLI prints version info and terminates as soon as it sees `--version`, regardless of whether `command` or `action` were set ([argument definition link](https://github.com/linode/linode-cli/blob/f970c001b68b39ef2b3b746945b830184e1dd807/linodecli/__init__.py#L71-L72), [argument usage link](https://github.com/linode/linode-cli/blob/f970c001b68b39ef2b3b746945b830184e1dd807/linodecli/__init__.py#L102-L106)).

Fixing this in a thorough way would probably involve creating command and action objects corresponding to both what's in the API spec and the commands that are in `__init__.py` currently so that this sort of ambiguous interpretation of arguments between different scopes can't happen.

**Comment by Dorthu** [comment]
Would it be offensive to rename the "version" argument of that endpoint for the CLI only?  I'm thinking a CLI-specific spec extension to rename it to something like `--kube-version` that would not impact the actual API schema.

**Comment by Dorthu** [comment]
This was fixed in https://github.com/linode/linode-cli/commit/e371922649d371b9e408e20d0af8a1fbb767b772 - closing
