### ISSUE TITLE
Update Linode site to point to the correct CLI guide

### ISSUE THREAD

**Issue by dkam** [linode/linode-cli#164]
Hi guys, 
The Linode product page for the CLI (https://www.linode.com/products/cli/) points to the deprecated version -> https://www.linode.com/docs/platform/api/using-the-linode-cli/   but should point to -> https://www.linode.com/docs/platform/api/linode-cli/

**Comment by displague** [comment]
This appears to be fixed via the docs update https://github.com/linode/docs/pull/2981

**Comment by Dorthu** [comment]
Confirmed that this is resolved, closing.
