### ISSUE TITLE
Create CAA records is not possible

### ISSUE THREAD

**Issue by Xananax** [linode/linode-cli#168]
It's impossible to create a CAA record with the current linode-cli:

```
linode -o domain -l domain.org -a record-create --name '' --ttl 3600 --type CAA --target issue "letsencrypt.org"
```
yields:

```
The record type must be one of the following: NS, MX, A, AAAA, CNAME, TXT, or SRV.
```

Yet, the GUI proposes to add CAA records:

![image](https://user-images.githubusercontent.com/836082/70861967-b00c7680-1f46-11ea-8c1d-22b842183d11.png)

 Looking [at the API](https://developers.linode.com/api/v4/domains-domain-id-records/#post), it seems it also doesn't cover CAA records, so maybe this should be taken upstream?

**Comment by Dorthu** [comment]
The CLI is generated off the API docs - maybe this value is just missing in the docs?  I'll look into this today.

**Comment by Dorthu** [comment]
Ah, I didn't realize until I started looking into this more - you're using the [old CLI](https://github.com/linode/cli) which is deprecated.  If you switch to this (the new) Linode CLI, this feature will work just fine.

This version of the CLI is presently only distributed via `pip`; to install this version of the CLI, run:

```bash
pip install linode-cli
```

The command to do what you're trying to do in this version of the CLI is as follows:

```bash
linode-cli domains records-create $DOMAIN_ID --type CAA --target "example.org" --name "" --tag "issue" --ttl 3600
```

I don't believe the old CLI is being supported, so I don't expect this bug would be fixed, but feel free to report it on that repo.

**Comment by Xananax** [comment]
You are correct!

I had installed it from the repo on Debian as proposed [in this article](https://www.linode.com/docs/platform/api/using-the-linode-cli/) (written on November 19, 2019, so not so old). If the Debian repo is not up to date or not considered a correct way to install `linode-cli`, it may be worth amending the article.

**Comment by Guaris** [comment]
I have a PR to fix this: https://github.com/linode/docs/pull/2981
