### ISSUE TITLE
Object Storage put: Error: RequestTimeTooSkewed

### ISSUE THREAD

**Issue by rafaelbernard** [linode/linode-cli#174]
Hello, everyone!

During an object storage put, I am receiving `Error: RequestTimeTooSkewed`. How may I leverage timeout?

- The source is a linode server at Freemont, CA
- Object Storage is at Newark, NJ
- File has 7G

**Comment by Dorthu** [comment]
Requests sent to object storage are time-sensitive; the signature that authorizes them is only valid for a small duration.   As such, this error can happen when the client's time is different than the server's time, making it appear as though the request is far older than the server would allow.

Can you run the following on the machine you're trying to do the upload from to confirm its time is reasonably in sync with the server? (please post the output here):

```bash
echo "Server Time:"; curl http://us-east-1.linodeobjects.com -v 2>&1 | grep '< Date: '; echo "Local Time:"; date -u
```

On my laptop right now, I get output like this: 

```
Server Time:
< Date: Mon, 23 Mar 2020 15:29:37 GMT
Local Time:
Mon Mar 23 15:29:37 UTC 2020
```

In my case, the server and my laptop agree on the time, and signatures from my laptop are seen as valid on the server.

**Comment by rafaelbernard** [comment]
@Dorthu thanks for your rreply. My output:

```
Server Time:
< Date: Mon, 23 Mar 2020 16:13:26 GMT
Local Time:
seg mar 23 16:13:26 UTC 2020
```

**Comment by Dorthu** [comment]
That looks fine.  I'm going to spin up a Linode in Freemont and see if I can reproduce this.

**Comment by Dorthu** [comment]
Sorry it took me a bit to get back to this.  I was unable to reproduce the error you described, although I did get a different one.

```bash
root@localhost:~# linode-cli obj put 7g-file my-bucket
7g-file
 |####################################################################################################| 100.0%
Error: EntityTooLarge
```

I think this "EntityTooLarge" error is because a file this large should be uploaded as a multipart upload (and it's not being done that way at present).  I'll get that implemented soon.

Can you reproduce the `RequestTimeTooSkewed` error with another tool, like s3cmd?

**Comment by rafaelbernard** [comment]
@Dorthu Using s3cmd I am fine. This is how I am uploading. s3cmd upload as multipart. Even sync command (with lots os large files) works pretty fine.

**Comment by Dorthu** [comment]
Ok, cool.  I'm going to get that implemented in the CLI and linked to this issue, might not be up until tomorrow.

**Comment by Dorthu** [comment]
This fix will be included in the CLI release happening later today.
