### ISSUE TITLE
unicodeencodeerror: 'utf-8' codec can't encode character '\udcd9' in position 20: surrogates not allowed

### ISSUE THREAD

**Issue by masoudkazemi** [linode/linode-cli#180]
Hi,
I'm trying to upload a document from a Nodejs script using linode-cli to Linode Object Storage. For most files it worked well. But for some files which include Persian words, it fails and returns the below error.
I should mention that I tried to upload the same file from command-line directly and it worked! So I also tried to utf8.encode the filename in the command runs from Nodejs script, but again the same error returned. Do you have any idea what's the problem here?

> Python 3.5.3
> linode-cli 2.13.1
> Built off spec version 4.14.0

error:
>  traceback (most recent call last):
>   file "/usr/local/bin/linode-cli", line 11, in <module>
>     sys.exit(main())
>   file "/usr/local/lib/python3.5/dist-packages/linodecli/__init__.py", line 373, in main
>     plugins.invoke(parsed.command, plugin_args, context)
>   file "/usr/local/lib/python3.5/dist-packages/linodecli/plugins/__init__.py", line 33, in invoke
>     plugin.call(args, context)
>   file "/usr/local/lib/python3.5/dist-packages/linodecli/plugins/obj.py", line 578, in call
>     command_map[parsed.command](client, args)
>   file "/usr/local/lib/python3.5/dist-packages/linodecli/plugins/obj.py", line 169, in upload_object
>     print(filename)
> unicodeencodeerror: 'utf-8' codec can't encode character '\udcd8' in position 0: surrogates not allowed

**Comment by Dorthu** [comment]
Thanks for the report!  To help me debug this, can you post a snippet of the Nodejs code you're using to upload the file and at least one character that's causing this error?

**Comment by masoudkazemi** [comment]
Actually, I keep debugging and find the problem.
The Nodejs process was running with Pm2 and there was some issue with Pm2. Removing the process from the Pm2 list and adding it again solved the issue!
It is very odd and I doubt if it is permanently solved or not. But I can say for sure it is not linode-cli's issue.

Anyway, as you asked here is the sample snippet:
```
const Promise = require('bluebird');
const shell = require('shelljs');

function execAsync(cmd, options = {}) {
  return new Promise(((resolve, reject) => {
    shell.exec(cmd, options, (code, stdout, stderr) => {
      if (code !== 0) {
        return reject(new Error(`${stdout} ${stderr}`));
      }
      return resolve(stdout);
    });
  }));
}

async function uploadFile(fullPath) {
  const cluster = 'eu-central-1';
  const bucket = 'bucket';
  const command = `linode-cli obj --cluster ${cluster} put '${fullPath}' ${bucket}`;
  await execAsync(command, { silent: true });
}

uploadFile('/home/user/آلبوم_کامل_دود_عود_ـ_محمدرضا_شجریان.mp4');

```
