### ISSUE TITLE
Total on 'linode-cli obj du' is in bytes, not xB

### ISSUE THREAD

**Issue by Oloryn** [linode/linode-cli#181]
When you do a 'linode-cl9i obj du' (which displays the size of each bucket, plus the total size used), the bucket sizes are displayed in KB, MB, or GB, but the total size is just displayed as a straight number (presumably in bytes).  Wouldn't it make sense to also display the total size in the appropriate units, instead of just in bytes?

**Comment by Dorthu** [comment]
That makes a lot of sense - I'll get this in this afternoon.  Thank you!

**Comment by Dorthu** [comment]
This should be included in the CLI release happening later today.  Thanks for the feedback!
