### ISSUE TITLE
it thinks you're installing a distribution when creating a swap disk

### ISSUE THREAD

**Issue by kenyon** [linode/linode-cli#187]
This might be a backend problem, but...

1. Create an empty Linode.
1. Create a system disk: `linode-cli  linodes disk-create 1234 --label system --size 10000 --image linode/debian10 --authorized_users my_username --root_pass somepassword`
1. Attempt to create a swap disk: `linode-cli  linodes disk-create 1234 --label swap --size 256 --filesystem swap`

```
Request failed: 400
┌errors─────┬─────────────────────────────────────────────────────┐
│ field     │ reason                                              │
├───────────┼─────────────────────────────────────────────────────┤
│ root_pass │ root_pass is required when deploying a distribution │
│           │ Distribution requires a minimum size of 1500        │
└───────────┴─────────────────────────────────────────────────────┘
```

Creating a swap disk at this point manually through Linode Manager works fine.

**Comment by kenyon** [comment]
BTW, what I'm really trying to do is create Linodes with non-default configuration profiles, because I don't like the defaults. If you could specify configuration profiles at the same time as creating Linodes, that would also solve the issue.

**Comment by Dorthu** [comment]
Can you try running the second command with `--no-defaults`?  If you configured a default image the first time you ran the CLI (or thereafter when running `linode-cli configure`) it will automatically be sent with all requests that accept it, including `disk-create`.

**Comment by Dorthu** [comment]
> If you could specify configuration profiles at the same time as creating Linodes, that would also solve the issue.

Unfortunately, when using the "fast method" of creating a new Linode, you can't specific things like kernel by design.  However, you can update the default configuration profile created for you after the fact; if you're writing a bash script it might look something like this: 


```bash
# create a new Linode and capture its ID
NEW_LINODE_ID=$(linode-cli linodes create --image linode/debian10 --root_pass $LINODE_PASSWORD --format 'id' --text --no-headers --booted no)

# look up the ID of the config created for that Linode
CONFIG_ID=$(linode-cli linodes configs-list $NEW_LINODE_ID --text --format 'id' --no-headers)

# update the config object
linode-cli linodes config-update $NEW_LINODE_ID $CONFIG_ID --kernel some-kernel
```

Above I used `--format` to limit the data returned by the CLI to just the ID, and `--text --no-headers` to get back just the data without headers or formatting.  You can also use `--json` to get back JSON data if that's easier to worth with.

**Comment by kenyon** [comment]
Ahh, duh, the defaults, thanks! I even saw #58 before creating this issue, but it didn't occur to me that the defaults would apply for `disk-create` too.

I just added `--no-defaults` to all of my commands and it works perfectly now. I'm using Ansible to script Linode creation: https://github.com/kenyon/ansible-playbooks/commit/e291bb4d01ff22b44fbde542e326d810ef4920ff (the [retry feature](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met) is a great way to handle the "not ready" status)
