### ISSUE TITLE
ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by elarroba** [linode/linode-cli#193]
Hello,

After installing and configuring the CLI I get the following error when executing:

> linode-cli obj ls

The **boto** library has been installed.
Any assistance would be greatly appreciated.

Thanks

Error

`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)`

**Comment by elarroba** [comment]
Found the solution. I'm using the CLI on macOS.
Go to the Applications folder, find your version of python & run the Install Certificates.command.
I'm closing this issue.
Thanks!

**Comment by Dorthu** [comment]
Thanks for the report!  I'm glad you figured it out, but I'm going to see if I can reproduce this on a clean OS X and add a more helpful error in that case.
