### ISSUE TITLE
Unable to update MX records

### ISSUE THREAD

**Issue by MaxXor** [linode/linode-cli#197]
Hi, updating an existing MX record fails with:

```
Request failed: 400
┌errors──┬─────────────────────────────────────┐
│ field  │ reason                              │
├────────┼─────────────────────────────────────┤
│ weight │ Cannot specify weight for MX record │
│ port   │ Cannot specify port for MX record   │
└────────┴─────────────────────────────────────┘
```

Request:

```
linode-cli domains records-update --ttl_sec "10800" $DOMAIN_ID $RECORD_ID
```

**Comment by Dorthu** [comment]
I cannot reproduce this on my account, although I do get a different error:

```bash
$ python3 -m linodecli domains records-update $DOMAIN_ID $RECORD_ID --ttl_sec 1000
Request failed: 400
┌errors─┬─────────────────────┐
│ field │ reason              │
├───────┼─────────────────────┤
│ type  │ Invalid record type │
└───────┴─────────────────────┘
```

If I include a `--no-defaults`, this error disappears; I think it was sending my configured Linode Type as the "type" field here.

If you re-run the command with `--debug` you should get detailed output about the request that's being sent; can you paste in a redacted version of the request body here?  I expect it would only include "domainId", "recordId",  and "ttl_sec".  If you'd rather not do so on github, please [open a support ticket](https://cloud.linode.com/support/tickets) linking to this issue and requesting it be forwarded to wsmith so I can take a look at your account and see what's differnet.

**Comment by MaxXor** [comment]
It does include only the specified arguments, as expected.

```
{"domainId": 123, "recordId": 123, "ttl_sec": 10800}
```

The existing domain record looks like this:

```
───────────────────────────────────────────────────────────────────────┬─────────┬──────────┬────────┐
│ id       │ type  │ name            │ target                          │ ttl_sec │ priority │ weight │
├──────────┼───────┼─────────────────┼─────────────────────────────────┼─────────┼──────────┼────────┤
│ 123      │ MX    │                 │ mail.domain.com                 │ 0       │ 10       │ 5      │
├──────────┼───────┼─────────────────┼─────────────────────────────────┼─────────┼──────────┼────────┤
```

**Comment by Dorthu** [comment]
Thanks for the info.  Looking more into it, it looks like an upstream issue; the API does not allow setting weight and priority for MX records, but this MX record already has those set.  I'm forwarding this along to our API team and get it resolved there; I'll keep you updated here.

Supposing you don't need the weight and priority set, you can include `--weight 0 --priority 0` to clear those fields and allow the update to complete successfully.

**Comment by MaxXor** [comment]
Thanks, I couldn't even update the existing record in the web interface of linode. Maybe it was some left-over record in the database (created in 2018) which was never updated according to the new rules? However deleting it and re-creating it without a weight worked fine.

**Comment by Dorthu** [comment]
That's what it looks like to me, too - I can't get a record in that state through the API or Cloud, but if I alter it manually I get the same errors you were seeing.  We've got a ticket for it; going forward we'll handle that unexpected state so that records can still be updated.

**Comment by Dorthu** [comment]
Several fixes were shipped to the DNS endpoints recently, and I believe they cover this situation.  Are you still encountering this issue?
