### ISSUE TITLE
Secure non-interactive ways for specifying the root password

### ISSUE THREAD

**Issue by gsauthof** [linode/linode-cli#200]
The linode-cli help and official guides tell me to either enter the root password interactively or on the command line. Thus, for non-interactive uses one has to specify the root password on the command line.

This is suboptimal as specifying the password on the command line is very insecure because any other local user can observe it via `ps`, `top` or by looking into `/proc/...`.

The standard practice to resolve such issues is to let the user alternatively supply a password via a file and/or an environment variable.

Example commands that implement these mechanisms: `virt-builder` and `psql`.

Note that - on Linux - environment variables of a process aren't accessible by other users (except for the root user).

Thus, please add a more secure way to supply the root password when creating linodes in an non-interactive way.

**Comment by Dorthu** [comment]
Makes sense.  I'll give this a look.  Thank you for the suggestion!

**Comment by Dorthu** [comment]
Opened #202 to allow accepting password fields from environment variables as suggested.  Let me know if this satisfies your needs, and thanks again for pointing this out.

**Comment by gsauthof** [comment]
Yes, this definitely satisfies my needs. Thanks for the quick change.

**Comment by Dorthu** [comment]
Excellent.  This was released in version 3.0.0 - should just need a `pip install --upgrade linode-cli` to get it
