### ISSUE TITLE
Accept script filename when updating or creating it

### ISSUE THREAD

**Issue by gsauthof** [linode/linode-cli#201]
It's unexpected that I have to use

```
linode-cli stackscripts update --script "$(cat ssh-host-key-stackscript.sh)" 660652
```

instead of the simpler and more convenient

```
linode-cli stackscripts update --script ssh-host-key-stackscript.sh 660652
```

Please also add a way to read a script directly from a file.

I think reading scripts directly from files is genuinely more useful than using the verbatim option value thus perhaps you also want to deprecate the current way. I mean StackScripts are always multi-line, most likely longer than a few lines thus it's getting cumbersome to supply them as option value, fast.

Currently, e.g. the update help reads

```
usage: linode-cli [-h] [--label label] [--description description]
                  [--images images] [--is_public is_public]
                  [--rev_note rev_note] [--script script]
                  stackscriptId

Update StackScript

positional arguments:
  stackscriptId

optional arguments:
  -h, --help            show this help message and exit
  --label label
  --description description
  --images images
  --is_public is_public
  --rev_note rev_note
  --script script
```
i.e. the `--script` option doesn't have a description that points out that the script indeed has to be specified inline. Since the value to `--is_public` is just a non-descriptive `is_public` marker (which doesn't point out which are valid values - perhaps true/false, perhaps 0/1 or even yes/no - we don't know) thus `script` could also be similar non-descriptive and as well be a placeholder for filename!

**Comment by Dorthu** [comment]
This feature was released in version 3.1.1 just a few minutes ago
