### ISSUE TITLE
How to run a bash script on a newly created VPS?

### ISSUE THREAD

**Issue by GildedHonour** [linode/linode-cli#212]
Say, I have a custom bash script which I want to run upon creation a new VPS server. How will I run a bash script?

**Comment by Dorthu** [comment]
Are you looking for this script to run once when the instance is created?  If so, you should look into StackScripts.

If you have the script you want to run, you can add it to your own StackScript library like so:

```bash
linode-cli stackscripts create --label "script-name" --is_public no --script /path/to/myScript.sh --images "linode/debian10" --images "linode/debian9"
```

(You can replace the values of `--images` with the ids of Linode-provided images the script can run on, in this example Debian 9 and Debian 10.  You can see all available images with `linode-cli images list`)

Once your StackScript is created, note the id returned and you can use it like this:

```bash
linode-cli linodes create --region us-east --type g6-standard-2 --image "linode/debian10" --root_pass --stackscript_id $myStackScriptID
```

(That's a normal Linode Create command with a `--stackscript_id` included; please note that the `--image` included here has to match one of the `--images` used when creating the StackScript).

And that's it - the Linode will be created and that script will run.  For more information on StackScripts and their advanced features, see the [StackScript guides](https://www.linode.com/docs/guides/platform/stackscripts/).

**Comment by GildedHonour** [comment]
Thx

**Comment by GildedHonour** [comment]
Is there a way to run a script or bash command not right after a server has been created, but on demand, and multiple times? Something like

```
linode-cli linodes <linode_id> --run_command <command123>

```
