### ISSUE TITLE
--no-defaults still necessary when using env variable

### ISSUE THREAD

**Issue by yormi** [linode/linode-cli#214]
The #140 issue does not seem fixed for:

`linode-cli obt put x y`
`linode-cli obj put --help`

Then, once I found the `--no-defaults` trick in #140, I got a:

> Error: cluster is required.

And I haven't seen anything about this in the README nor [here](https://www.linode.com/docs/guides/linode-cli/).

### Feedback on User Experience

It feels weird that it's impossible to get the `--help` without having configured the tool.

I'm trying to have a docker container backup my database and I found it a bit difficult to user `linode-cli` without interaction.

1. The help is unavailable without initializing the config
2. With the env variable, there is the #140 issue
3. There is no info about where is the configuration file (found it in the #148 PR file :P )

### Version

3.2.1

It's not the worst problem ever but Linode is pretty good with user experience (in my experience) so I thought you might appreciate the feedback.

Cheers !

**Comment by Dorthu** [comment]
Thanks for the feedback!  I'll take a look into this today; I don't know that I'd tested the obj integration without a config file before, and it does seem weird that `--help` won't work without configuration.

**Comment by yormi** [comment]
No worries !

Have a great day :)

**Comment by Dorthu** [comment]
I ran through the CLI without a config present and fixed the issues I came across in #216, especially the issue that `--help` wasn't accessible without a config.

**Comment by yormi** [comment]
Wow that was quick !
Great job !
Thanks from everybody that won't have to struggle with this :)
--

Guillaume Lambert
Automatisation Orisha - *Produire plus, avec moins, plus facilement !*

orisha.ca <https://www.products.orisha.io/francais>
*1-888-267-4742* <1-888-267-4742>
940 rue Pouliot
Québec, QC, G1V 3N9
