### ISSUE TITLE
Add label filtering to cluster-list

### ISSUE THREAD

**Issue by DazWilkin** [linode/linode-cli#221]
I was unable to find a way (without using `jq`) to filter clusters:

```bash
linode-cli lke clusters-list --label=${LABEL} ...
```

In a similar vein to:

```bash
linode-cli linodes list --label=${LABEL} ...
```

This is a useful way to grab one (few) of many results.

Am I overlooking equivalent functionality in the CLI for LKE?

**Comment by lgarber-akamai** [comment]
Closing as `label` is now a properly supported filterable field for LKE clusters. Feel free to @ me if this is still an issue :slightly_smiling_face:

**Comment by DazWilkin** [comment]
Outstanding! Thank you
