### ISSUE TITLE
linode-cli v5: The API responded with version 4.86.0, which is newer than the CLI's version of 4.85.0.  

### ISSUE THREAD

**Issue by l8gravely** [linode/linode-cli#227]
Even though I'm using linode-cli v5.0.0, I still get complaints about the API versions not being correct:

$ linode-cli --json linodes ips-list 12345 --format private
The API responded with version 4.86.0, which is newer than the CLI's version of 4.85.0.  Please update the CLI to get access to the newest features.  You can update with a simple `pip install --upgrade linode-cli`
[{"ipv4": {"private": [{"address": "192.168.xxx.yyy", "gateway": null, "subnet_mask": "255.255.128.0", "prefix": 17, "type": "ipv4", "public": false, "rdns": null, "linode_id": 12345, "region": "us-central"}]}}]

$ linode-cli --version
linode-cli 5.0.0
Built off spec version 4.85.0

Which really makes me think you guys should have released linode-cli v4.85.x instead of v5.0.0 when you did the major version bump.

**Comment by Dorthu** [comment]
Version 5.0.1 was published this morning, and is built off a newer spec version.  You should be able to upgrade to it with `pip install --upgrade linode-cli` or `pip install linode-cli==5.0.1`.  You can also disable these messages with `--suppress-warnings`
