### ISSUE TITLE
Can't install properly

### ISSUE THREAD

**Issue by AndresCalvo** [linode/linode-cli#232]
Hello, I'm trying to install the Linode CLI on Windows 10, but it doesn't seem to work. I'm kind of new to using the CLI so I assume I must be doing something wrong, but can't figure out what is it.
For the installation, I run;
>pip install linode-cli --upgrade

Which finishes with no errors. However, whenever I try to run any linode-cli command, I get the "linode-cli not recognized as an internal or external command" message.

**Comment by Dorthu** [comment]
Thank you for the report!   We're looking into this issue and will keep you updated.

**Comment by AndresCalvo** [comment]
Update:
I Managed to get it working; no idea why it happened but instead of:
>linode-cli <command>
I do:
>python linodecli <command>
Then it works, but i'd still like to know why, and fix it if possible. It is kind of tiring writing that extra python word for every command.

**Comment by Dorthu** [comment]
I haven't been able to test this yet - I don't have ready access to a Windows 10 machine 🙃   

I suspect something is off with your `PYTHONPATH` environment variable.  I think you can pint that with `echo %PYTHONPATH%` (or `echo $Env:PYTHONPATH` in powershell?).   I'd be interested to see how that lines up with the "Location" printed by `pip show linode-cli` (which is where the cli code was installed).

**Comment by AndresCalvo** [comment]
Well indeed, looking carefully at the PATH var, I noticed that there were a few left-over files from some old python version I installed on my PC years ago and apparently it was conflicting with the directory where my currect python operates from. Made a clean re-installation of python and now it works just fine.

Bottom line, it was all beacause of poor "house-keeping" on my PC.
