### ISSUE TITLE
Running linode-cli without Linode Personal Token

### ISSUE THREAD

**Issue by superherointj** [linode/linode-cli#235]
I have upgraded [`linode-cli` package for NixOS](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/virtualization/linode-cli/default.nix) to latest. But I did run into an issue of linode-cli requiring Linode Personal Token for basic things as showing `version` and `completion bash`. Currently tests are disabled. I need to use these commands without Linode Personal Token, because Hydra (the service that runs CI) won't have a Linode Personal Token. 

I need to run linode-cli without Linode Personal Token to:
1) check built version.
2) generate bash completions

Any idea?

Thanks.

**Comment by Dorthu** [comment]
I agree that a token should not be required to run these simple commands that don't make any requests, and I'll look at making that default behavior.  In the meantime, you can use the `--skip-config` flag to tell the CLI not to prompt for configuration, which should allow your CI pipeline to work without a token.

**Comment by superherointj** [comment]
Thanks!
