### ISSUE TITLE
Recursive delete of files in a bucket

### ISSUE THREAD

**Issue by KeithCu** [linode/linode-cli#236]
I've got a few test buckets I've setup with 350 little files.

Unfortunately, linode-cli obj doesn't seem to support recursive delete. It appears I have to use s3cmd, which I can't use because the current released version doesn't work Python 3.9. Can you please add support for: 

- recursive delete, and / or
- the ability to delete a non-empty bucket?

Thanks!

**Comment by Dorthu** [comment]
This should be included in the next CLI release, expected this afternoon
