### ISSUE TITLE
What is the image format used for Linode  / linode-cli image-upload plugin

### ISSUE THREAD

**Issue by barnscott** [linode/linode-cli#243]
[ Not an issue, information request ]

Plugins provide the following:

https://github.com/linode/linode-cli/blob/master/linodecli/plugins/image-upload.py

`linode-cli image-upload --region us-east --label my-image /path/to/image.gz`

What is the format of `image.gz` ?  

tar.gz ?  qcow2.gz ? raw ?

**Comment by barnscott** [comment]
Think i found it,  `raw.gz` from here:

https://www.linode.com/docs/guides/linode-images/#uploading-an-image

Thanks,

**Comment by Dorthu** [comment]
Glad you found it.  I'll make sure the answer is in the help though - shouldn't need to go hunting for docs to use the CLI
