### ISSUE TITLE
example CLI command for firewalls create in API docs results in error

### ISSUE THREAD

**Issue by lpmi-13** [linode/linode-cli#249]
The command shown in the CLI reference at https://www.linode.com/docs/api/networking/#firewall-create doesn't work.

```
linode-cli firewalls create \
  --rules '{"inbound": [{"protocol": "TCP", "ports": "22, 80, 8080, 443", "addresses": {"ipv4": ["192.0.2.1", "192.0.2.0/24"], "ipv6": ["2001:DB8::/32"]}}]}' \
```
outputs the following error:

```
linode-cli: error: ambiguous option: --rules could match --rules.inbound.protocol, --rules.inbound.ports, --rules.inbound.addresses.ipv4, --rules.inbound.addresses.ipv6, --rules.inbound.action, --rules.inbound.label, --rules.inbound.description, --rules.outbound.protocol, --rules.outbound.ports, --rules.outbound.addresses.ipv4, --rules.outbound.addresses.ipv6, --rules.outbound.action, --rules.outbound.label, --rules.outbound.description, --rules.inbound_policy, --rules.outbound_policy
```

I've been fighting the cli to try and create a firewall with multiple rules for the past 2 hours and have no idea what the expected command syntax would be.

I'll probably just resort to using the REST API to get it working, but would be very nice to able to use the cli for everything.

**Comment by Dorthu** [comment]
Thanks for the report!  It looks like the documentation is not the same as what the CLI currently expects, and I'm not sure the CLI is doing the right thing if given what it's currently expecting either.  I'm going to see if I can get it working and report back.

**Comment by Dorthu** [comment]
I did some tinkering with the docs, and I think this is going to be the resulting command format:

```bash
$ linode-cli firewalls create \
  --label test \
  --rules.inbound_policy DROP \
  --rules.outbound_policy DROP \
  --rules.inbound '[{"addresses":{"ipv4":["12.34.56.78/32"]},"action":"ACCEPT","protocol":"TCP"},{"addresses":{"ipv4":["12.34.56.79/32"]},"action":"DROP","protocol":"TCP"}]' \
  --rules.outbound '[{"addresses":{"ipv4":["12.34.56.77/32"]}, "action":"DROP", "protocol":"TCP"}]'

```

The resulting help will look like:

```bash
$ linode-cli firewalls create --help
linode-cli firewalls create
Firewall Create

Arguments:
  --label: (required) The Firewall's label, for display purposes only.
  --status: The status of this Firewall.
  --rules.inbound: (I'll fill this in.)
  --rules.outbound: (I'll fill this in too.)
  --rules.inbound_policy: The default behavior for inbound traffic.
  --rules.outbound_policy: The default behavior for outbound traffic.
  --tags: An array of tags applied to this object.
```

I'll have a PR up against the linode-api-docs repo to make these changes shortly, but if you have any feedback on the command format I'm open to it.

**Comment by Dorthu** [comment]
The above changes are proposed in https://github.com/linode/linode-api-docs/pull/484 - once that's merged in an a new CLI build released, this should work as expected.  I'll update this issue when that happens.  Sorry for the frustration.

**Comment by lpmi-13** [comment]
Hey there, thanks for the quick turnaround! The new example output from `linode-cli firewalls create --help` looks great.

The only additional suggestion I would add is to explicitly specify that both `--rules.inbound` and `--rules.outbound` are expected as JSON arrays, rather than just mentioning JSON.

I remember looking at the current help output and being totally confused as to which data type each of the cli flags was expecting. I mean, it's super obvious to me now having discussed it, but it wasn't at all when I first started investigating.
