### ISSUE TITLE
linode-cli-5.5.1 fails during upload.

### ISSUE THREAD

**Issue by applemuncy** [linode/linode-cli#252]
I'm impressed by the quick turnaround on issue 250 but now I'm your tester : )
Did the update to 5.5.1 but it bails out about 1/3 way though upload
[linode-cli-output.txt](https://github.com/linode/linode-cli/files/6811675/linode-cli-output.txt)
.

**Comment by Dorthu** [comment]
Thanks for giving it a try 😄 I don't think that fix has made it into a release yet, though; 5.5.1 went out before it was merged yesterday.  I'll see if I can get it into 5.5.2 this morning.

**Comment by Dorthu** [comment]
I suspect the issue you encountered last night was due to [an unrelated networking problem in Newark](https://status.linode.com/incidents/xc3x0t0dqbh4); uploading images appears to work now.  I'll update this again once 5.5.2 is released.

**Comment by applemuncy** [comment]
HAHA, Newark you say : )
Yes, thought had occurred to me that might have been a one off failure.

**Comment by Dorthu** [comment]
5.5.2 is now available

**Comment by LBGarber** [comment]
Closing this issue because it seems to be resolved. Feel free to tag me if any related issues are still occurring 🙂
