### ISSUE TITLE
Releases after v5.5.3 don't appear via pip

### ISSUE THREAD

**Issue by felicianotech** [linode/linode-cli#259]
I'm not seeing the latest releases on pip which is causing my snap of the Linode CLI ([ref](https://github.com/felicianotech/snap-linode-cli)) to fail. Anyone know what's up?

**Comment by Dorthu** [comment]
Hey Ricardo!  I just pushed up a fix for a test that was failing, which caused our automated builder/publisher to fail.  The latest release should be in pypi shortly.

**Comment by felicianotech** [comment]
Thanks Will! I hope you're doing well.

👍🏼
