### ISSUE TITLE
Pypi project name different from file download

### ISSUE THREAD

**Issue by ryantm** [linode/linode-cli#28]
I was trying to package `linode-cli` for NixOS and I noticed a couple issues with the release artifacts. I'll post a separate issues about them.

The pypi project name is `linode-cli`, but the first part of the file download is `linode_cli`  in `https://files.pythonhosted.org/packages/18/3f/4820d8353159394601a55f08d49073e9ba88b194c9ef15afaa5f38e1cce3/linode_cli-2.0.0-py2.py3-none-any.whl`

It would be nice if those names were the same.

It's also a bit unfortunate that this project has the exact same name as the Perl-based binary published by Linode.

**Comment by Dorthu** [comment]
> It would be nice if those names were the same.

I'll look into it, but I think there was an issue with the hyphen in the file or package name that made me have to change it.

> It's also a bit unfortunate that this project has the exact same name as the Perl-based binary published by Linode.

This is replacing the perl version of the Linode CLI - that version targeted our old API, and is deprecated.
