### ISSUE TITLE
Provide fish completion

### ISSUE THREAD

**Issue by rombert** [linode/linode-cli#281]
It would be great if fish completion could be provided out-of-the-box, similar to the existing bash completion.

**Comment by SolidRhino** [comment]
It should be awesome if this was available out-of-the-box.

@rombert Have you found a workaround?

**Comment by rombert** [comment]
@SolidRhino - nope, no workaround.

**Comment by lgarber-akamai** [comment]
This functionality has been released in [v5.28.0](https://github.com/linode/linode-cli/releases/tag/v5.28.0). 

Let us know if you run into any other bugs or have any feature suggestions!
