### ISSUE TITLE
Add ability to configure token with one command

### ISSUE THREAD

**Issue by SebDanielsson** [linode/linode-cli#295]
When running scripts it would be nice if we could just run linode-cli configure --token <api-token> to configure linode-cli. Currently when running that command I get the following output:
```
Welcome to the Linode CLI.  This will walk you through some initial setup.

First, we need a Personal Access Token.  To get one, please visit
https://cloud.linode.com/profile/tokens and click
"Create a Personal Access Token".  The CLI needs access to everything
on your account to work correctly.
Personal Access Token: 
```

**Comment by Dorthu** [comment]
Configuring the CLI is generally intended for interactive use; would setting up a token in the environment cover your use-case?  If so, you can already do that:

```bash
export LINODE_CLI_TOKEN="some-token"
# now you can use the CLI without a config file present
linode-cli linodes create --region us-east --type g6-standard-1 --image linode/debian10 --root_pass $PASSWORD 
```

If this doesn't solve your problem, could you give me more information about what you're trying to do?

**Comment by SebDanielsson** [comment]
That solved my problem!☺️

I use Terraform to create and configure my VMs. Since the normal Linux reboot command doesn't bring up the OS again I simply configure the reboot command to run linode-cli and reboot the whole machine that way instead☺️

**Comment by Dorthu** [comment]
Glad to hear it!
