### ISSUE TITLE
Linode firewalls - unrecognized arguments: --status

### ISSUE THREAD

**Issue by solairen** [linode/linode-cli#306]
In the [documentation](https://www.linode.com/docs/api/networking/#firewall-update) there is information on how to disable the firewall using CLI.

```bash
linode-cli firewalls update 123 \
  --status disabled
```

When I tried to use it I got an error:

```bash
linode-cli firewalls update: error: unrecognized arguments: --status disabled
```

Is the documentation outdated or is this feature missing in the CLI?

**Version:**
linode-cli 5.23.0
Built off spec version 4.136.0

**Scenario to reproduce:**
1. Create an API token that contains firewalls.
2. Log in to Linode using linode-cli
3. Get firewall id: `linode-cli firewalls list`
4. Run command to disable the firewall: `linode-cli firewalls update <FIREWALL_ID> --status disabled`

**Reproduction rate:**
100%

**Actual result:**
```bash
linode-cli firewalls update: error: unrecognized arguments: --status disabled
```

**Comment by LBGarber** [comment]
@solairen Thanks for the report!

It looks like this field was specified in the corresponding [OpenAPI spec entry](https://github.com/linode/linode-api-docs/blob/development/openapi.yaml#L13816), but was using an existing `readOnly` component that was not being properly handled. 

I've put up a [PR](https://github.com/linode/linode-api-docs/pull/688) to fix this issue in our spec repository.

Let us know if you run into any other issues :slightly_smiling_face:
