### ISSUE TITLE
Publish source dist to pypi?

### ISSUE THREAD

**Issue by chenrui333** [linode/linode-cli#328]
👋 I wonder if it makes sense to publish the source dist to pypi? I would help downstream packaging to resolve/auditing the dependencies. Thanks!

**Comment by lgarber-akamai** [comment]
Thanks for the request!
This should be fairly simple for us to integrate into our release process; I'll bring this up with my team and get back to you 🙂

**Comment by chenrui333** [comment]
Thanks @lgarber-akamai!

**Comment by lgarber-akamai** [comment]
@chenrui333 The relevant PR has been merged and source dists should be available on PyPI starting with the next release! 🎉
