### ISSUE TITLE
linode-domain record-create parsing issue

### ISSUE THREAD

**Issue by DarrylHon** [linode/linode-cli#33]
When a TXT record value starts with a minus/hyphen char, the linode-domain cli tool reports a parsing error. The behavior is the same when tested with double or single quotes. Issuing the same command without the leading minus/hyphen char works as expected.

Creating record with the following command:
```
linode-cli domains records-create 459068 --type TXT  --name _acme-challenge --target -xrOw1XWVekOhIbtSMfrFkce4Cgf5jczfKqZqD6H05I
linode-cli: error: argument --target: expected one argument
```

**Comment by Dorthu** [comment]
I can reproduce this issue, looking into it now

**Comment by Dorthu** [comment]
Looks like this is an unfortunate quirk of python's `argparse` module (which is being used here).  I'm going to keep this open and look for a workaorund, but the following works for me if you need a fix in the meantime: 

```
linode-cli domains records-create 459068 --type TXT  --name _acme-challenge --target="-xrOw1XWVekOhIbtSMfrFkce4Cgf5jczfKqZqD6H05I"
```

**Comment by DarrylHon** [comment]
Thank you for looking into this; I completely overlooked adding that simple equal sign.

**Comment by Dorthu** [comment]
No problem!  I did some research into this over the past couple weeks and didn't come up with any way to convince argparse to take arguments that start with a `-` - is quoting it with an `=` an acceptable solution?

**Comment by Dorthu** [comment]
Closing this since it's been stale for two weeks
