### ISSUE TITLE
make install failed on Ubuntu 17.10

### ISSUE THREAD

**Issue by ginkgomzd** [linode/linode-cli#34]
using master or latest 2.x tag
```
mzd☯ artichoke :>sudo make install SPEC=https://developers.linode.com/openapi.yaml
python linodecli bake https://developers.linode.com/openapi.yaml --skip-config
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/share/linode-cli/linodecli/__main__.py", line 3, in <module>
    from linodecli import main
ImportError: No module named linodecli
Makefile:20: fallo en las instrucciones para el objetivo 'common'
make: *** [common] Error 1
```

**Comment by ginkgomzd** [comment]
I tried this, which looks like an error to me (I don't know any python).

```
mzd☯ artichoke :>git diff
diff --git a/Makefile b/Makefile
index 45c3c41..a3bb0d0 100644
--- a/Makefile
+++ b/Makefile
@@ -17,7 +17,6 @@ build: common
        $(PYCMD) setup.py bdist_wheel --universal
 
 common:
-       python linodecli bake ${SPEC} --skip-config
-       python3 linodecli bake ${SPEC} --skip-config
+       $(PYCMD) linodecli bake ${SPEC} --skip-config
        cp data-2 linodecli/
        cp data-3 linodecli/

```
... but there was no change in the error, other than

**Comment by ginkgomzd** [comment]
so, I got brave, and I googled, and I changed __main__.py

```
root@localhost:/usr/local/sbin/linode-cli# git diff
diff --git a/linodecli/__main__.py b/linodecli/__main__.py
index 98f3fa9..47153f7 100644
--- a/linodecli/__main__.py
+++ b/linodecli/__main__.py
@@ -1,5 +1,5 @@
 from __future__ import absolute_import
 
-from linodecli import main
+from __init__ import main
 
 main()
```

Which appears to have worked, but then hit another error:
```
  File "linodecli/__init__.py", line 6, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

**Comment by Dorthu** [comment]
I think I got it - can you please pull master and verify it fixed so I can close this?

**Comment by ginkgomzd** [comment]
It does look like the first error I reported is fixed, but it is again getting stuck on the second, for "pkg_resources"

```
root@localhost:/usr/local/sbin/linode-cli# make install
python -m linodecli bake  --skip-config
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "linodecli/__init__.py", line 6, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
Makefile:20: recipe for target 'common' failed
make: *** [common] Error 1
root@localhost:/usr/local/sbin/linode-cli# 
```

P.S. - I'm now testing on a fresh linode ubuntu 18.04 LTS image. This was on a fresh clone of the repo too, and I verified your commit from today was included.

Cheers

**Comment by Dorthu** [comment]
Alright, I'm spinning up a new Ubuntu 18.04 now - I'll report back in a little bit

**Comment by Dorthu** [comment]
Sorry for the delay - give it another go, the new instructions/commands worked for me on a fresh Ubuntu 18.04 Linode.

**Comment by ginkgomzd** [comment]
great! I finally got a successful setup on my 17.10 workstation.

I had to address some missing prerequisites and run it a few times. 
I also had to run as sudo... not sure if that is my system, or a normal requirement that should be noted in the README.

I created a PR that incorporates your new build steps into `make install`.
I realized after why you maybe want to keep `install` and `build` distinct. Maybe to improve on my PR, you should use an empty file called `build` (by putting `touch build` at the end of the make recipe). That way, someone could do a build with a different spec, and not have install clobber it by running build again.

Thanks for all your work!
Cheers
