### ISSUE TITLE
[Feature]: allow to merge kubeconfig of lke cluster using cli without having to do that manually

### ISSUE THREAD

**Issue by w7089** [linode/linode-cli#347]
### Description

Currently, after creation of lke cluster using linode-cli, one has to download and process cluster's kubeconfig as described in https://github.com/linode/linode-cli/issues/247. 

Suggest to have an option to merge cluster's kubeconfig to ~/.kube/config similar to https://docs.aws.amazon.com/cli/latest/reference/eks/update-kubeconfig.html 

### Potential Usage Example

`linode-cli lke kubeconfig-view [cluster_id] --merge-to-kubeconfig`

**Comment by jriddle-linode** [comment]
Thanks for the suggestion, right now our goal is to keep the CLI itself as generic as possible as its generated from our OpenAPI Spec. This however could be made into a plugin which is intended more for hardcoded features. I'm not very well versed on the application of merging kubeconfig but i'll create a ticket for the team to investigate this and see what it takes to make a plugin for it. We'll let you know if we have any questions!

**Comment by acrogenesis** [comment]
@w7089 I made this bash function to save a kube config and merge with whatever is there.
```bash
lke-save() {linode-cli lke clusters-list --json | jq ".[]  | select(.label == \"$1\") | .id" | xargs -I {} linode-cli lke kubeconfig-view {} --text | sed 1d | base64 --decode | yq -i eval-all '. as $item ireduce ({}; . *+ $item)' ~/.kube/config -}
```
Add that to your `.bashrc` and run it `lke-save cluster-name`

**Comment by acrogenesis** [comment]
@jriddle-linode `yq` which is the cli I'm using to merge the yamls is also available in python https://kislyuk.github.io/yq/.

**Comment by jriddle-linode** [comment]
thanks @acrogenesis for sharing the work around, I like seeing how people are scripting the CLI, please feel free to share other stuff you use it helps us learn how to expand on the CLI

**Comment by acrogenesis** [comment]
This works a bit better at merging the files and also sets the context to that cluster
```bash
lke-save() {
  local id=$(linode-cli lke clusters-list --json | jq ".[]  | select(.label == \"$1\") | .id")
  linode-cli lke kubeconfig-view $id --text | sed 1d | base64 --decode | yq -i eval-all '. as $item ireduce ({}; . *=n $item)' ~/.kube/config - && kubectl config use-context lke$id-ctx
}
```
