### ISSUE TITLE
[Bug]: calling help on alias does not show anything

### ISSUE THREAD

**Issue by rouzier** [linode/linode-cli#351]
### CLI Version

linode-cli 5.29.0 Built off spec version 4.143.1

### Command

linode-cli linodes ls --help

### Expected Behavior

linode-cli linodes ls --help
linode-cli linodes list
Linodes List
API Documentation: https://www.linode.com/docs/api/linode-instances/#linodes-list

You may filter results with:
  --label
  --region
  --image
  --group
  --tags
  --id
  --ipv4

### Actual Behavior

Shows nothing

### Steps to Reproduce

linode-cli linodes ls --help

**Comment by jriddle-linode** [comment]
Thanks for the bug report! We'll take a look at this soon and get a PR up.

**Comment by lgarber-akamai** [comment]
@rouzier I've put up a pull request to resolve this issue and it should go out with our next scheduled release :slightly_smiling_face:

**Comment by rouzier** [comment]
I tried this on the latest release.
```
linode-cli -v
linode-cli 5.31.0
Built off spec version 4.144.1
```
Still the command below produces no output.
I am running this on Macos
```linode-cli linodes ls --help```

**Comment by lgarber-akamai** [comment]
Sorry about that, we did resolve the issue in the related PR but weren't able to merge it into the release quite yet due to some large internal refactors it relies on.

**Comment by rouzier** [comment]
Thank You for getting back to me
