### ISSUE TITLE
[Feature]: Official linode-cli github action setup

### ISSUE THREAD

**Issue by acrogenesis** [linode/linode-cli#360]
### Description

It would be great to have an official linode-cli github action setup. 
I've found only these two https://github.com/marketplace/actions/linode-authenticator https://github.com/marketplace/actions/linode-cli

**Comment by lgarber-akamai** [comment]
Thanks for the feature request! 

I definitely think an official linode-cli GitHub Action would come in handy for users looking to automate their infrastructure through CI/CD. I've added a ticket to our internal tracker to investigate this further.

In the meantime, feel free to let us know if you have any other feature requests or bug reports :slightly_smiling_face:

**Comment by lgarber-akamai** [comment]
@acrogenesis We've officially published a GitHub Action for setting up the Linode CLI in a GHA environment 🎉 

Take a look here: https://github.com/marketplace/actions/setup-linode-cli
