### ISSUE TITLE
[Bug]: Cannot filter linodes using image 

### ISSUE THREAD

**Issue by rouzier** [linode/linode-cli#370]
### CLI Version

linode-cli 5.31.0 Built off spec version 4.144.1

### Command

```linode-cli linodes list --image 'linode/rocky8'```

### Output

```
Request failed: 400
┌errors────┬────────────────────────┐
│ field    │ reason                 │
├──────────┼────────────────────────┤
│ X-Filter │ Could not apply filter │
└──────────┴────────────────────────┘
```

### Expected Behavior

A list of linodes filtered by image

### Actual Behavior

This error
```
Request failed: 400
┌errors────┬────────────────────────┐
│ field    │ reason                 │
├──────────┼────────────────────────┤
│ X-Filter │ Could not apply filter │
└──────────┴────────────────────────┘
```

### Steps to Reproduce

Every time I run the command above

**Comment by jriddle-linode** [comment]
strange seems to work with all the other filters but not image, i'll make a ticket to look into this.

**Comment by lgarber-akamai** [comment]
I've reached out to the appropriate teams internally to get this resolved. I'll let you know when we have any updates 🙂

**Comment by lgarber-akamai** [comment]
@rouzier This issue has been resolved in the latest Linode API release and should no longer occur in linode-cli. 

Let us know if you run into any other issues!

**Comment by rouzier** [comment]
Thank you it works!
