### ISSUE TITLE
[Bug]: Cannot remove axfr_ips from domain

### ISSUE THREAD

**Issue by guycoldham** [linode/linode-cli#371]
### CLI Version

linode-cli 5.31.0 Built off spec version 4.144.1

### Command

linode-cli domains update <domainID> --axfr_ips []

### Output

no matches found: []

### Expected Behavior

Remove any existing axfr_ips.

### Actual Behavior

error

**Comment by jriddle-linode** [comment]
Thanks for the issue! We currently don't support empty lists correctly, we're investigating a solution while we do large refactors of the codebase. Will update here when we have a better solution for handling empty lists for any call in the CLI.
