### ISSUE TITLE
[Bug]: linode-cli --version doesn't show the current version

### ISSUE THREAD

**Issue by w7089** [linode/linode-cli#382]
### CLI Version

5.32.1 Built off spec version 4.145.0

### Command

`linode-cli --version`

### Output

```
linode-cli building
Built off spec version 4.145.0
```

### Expected Behavior

`5.32.1` version to be shown

### Actual Behavior

`5.32.1` version not shown

**Comment by lgarber-akamai** [comment]
Hi there! 

Could you specify the command you used to install linode-cli (or the Docker image you're using if applicable) as well as your Python version? This will help narrow things down a bit 👍

**Comment by w7089** [comment]
Sure, `pip3 install linode-cli`. 

I'm using python 3.10

**Comment by lgarber-akamai** [comment]
@w7089 Thanks for the info!

It looks like the CLI is failing to grab the version [here](https://github.com/linode/linode-cli/blob/dev/linodecli/__init__.py#L29). I'll take a deeper look into this and let you know if I find anything.

**Comment by w7089** [comment]
Seems like the error got resolved in `5.33.0`
