### ISSUE TITLE
Please show ipv6 address at Linode creation time

### ISSUE THREAD

**Issue by willemdh** [linode/linode-cli#48]
See also https://github.com/linode/cli/issues/14

**Comment by Dorthu** [comment]
We have a new CLI release slated for early next week - I'll include this in it.  In the meantime, you can get the output you want with the `--format` flag (pass it a comma-separated list of attributes you want to see on output).  Here's an example of me creating a Linode and seeing the ID, ipv4 and ipv6 address as output (in tab-delimited text output for easy parsing):

```
wsmith@linode$ linode-cli linodes create --root_pass --format 'id,ipv4,ipv6' --text
Value for root_pass:
id	ipv4	ipv6
10337453	69.164.211.83	2600:3c03::f03c:91ff:fe22:88dc/64
```

You can omit the `--text` if you prefer the tabular output instead.

**Comment by willemdh** [comment]
Thanks!
