### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by youradds** [linode/linode-cli#487]
### CLI Version

linode-cli 5.41.2 Built off spec version 4.157.1

### Command

linode-cli domains records-update 123 1234556 --type AAAA --name www --target 2a01:7e00::f03c:92ff:fec4:c4f8

### Output

usage: linode-cli domains records-update [-h] [--name name] [--target target] [--priority priority] [--weight weight] [--port port] [--service service] [--protocol protocol] [--ttl_sec ttl_sec] [--tag tag] domainId recordId
linode-cli domains records-update: error: argument domainId: invalid int value: 'AAAA'

### Expected Behavior

To update the record to the new value

### Actual Behavior

Error

### Steps to Reproduce

Just run the command . It used to work fine as-is. I think something has broken in an update. I opened a Linode support ticket,  and he confirmed the bug but couldn't explain why. He suggested opening a ticket here as this is where its maintained from

I hope there is a simple fix - as its a PITA having to manually go in and update the IPs (my script used to do this all for me, when moving sites from one server to another)

Thanks

**Comment by youradds** [comment]
Thank you - that was it! I needed:

`linode-cli domains records-update $_->{id} $dns->{id} --name "$dns->{name}" --target $new_ip`

i.e not -type A / AAAA - I guess it works that out on its own, based on the input anyway? 

All working fine now =)

**Comment by lgarber-akamai** [comment]
Glad to hear! Let us know if you run into any other issues.
