### ISSUE TITLE
Cannot make StackScript public

### ISSUE THREAD

**Issue by Dorthu** [linode/linode-cli#5]
`linode-cli stackscript update <ID> -p` does not result in a public stackscript

**Comment by rmcintosh** [comment]
could be wrong but I think this is actually a bug in the python library:

```
client = LinodeClient('REAL_TOKEN')

stackscript = StackScript(client, REAL_ID)

stackscript.is_public = True

stackscript.save()
```

doesn't work and it also doesn't work when setting ```is_public``` to the string "true"

**Comment by Dorthu** [comment]
Hmm.. Thanks for looking at it, I'll investigate further
