### ISSUE TITLE
[Bug]: git clone git@github.com:linode/linode-cli.git

### ISSUE THREAD

**Issue by okyerejosephokraku60** [linode/linode-cli#516]
### CLI Version

5.24.0

### Command

git clone git@github.com:linode/linode-cli.git

### Output

Cloning into 'linode-cli'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Expected Behavior

Something good

### Actual Behavior

Cloning into 'linode-cli'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Steps to Reproduce

Can't list them.

**Comment by lgarber-akamai** [comment]
@okyerejosephokraku60 Thanks for the report!

To clone this repository you'll either need to [setup an SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh) or clone using the HTTPS URL:

```
git clone https://github.com/linode/linode-cli.git
```

**Comment by lgarber-akamai** [comment]
Closing since this issue doesn't seem to be specific to this project. Feel free to @ me if this issue is still relevant 🙂

**Comment by okyerejosephokraku60** [comment]
The issue has been solved bit the steps has been taken from GitHub
