### ISSUE TITLE
Node missing in kubernetes but linode-cli  shows all the nodes![Bug]: 

### ISSUE THREAD

**Issue by mzimry** [linode/linode-cli#559]
### CLI Version

linode-cli 5.45.2 Built off spec version 4.167.3

### Command

linode-cli lke pools-list $CLUSTER_ID
kubectl get nodes

### Output

linode-cli lke pools-list $CLUSTER_ID -> output is a list of all the nodes in my cluster (total of 6)
kubectl get nodes -> output is a list of 5 nodes. 1 was missing from the list

### Expected Behavior

both command should have the same amount of nodes in the list.

### Actual Behavior

the commands outputs were different. After recycling the missing node- the kubectl output behaved as expected- all nodes was listed.

**Comment by lgarber-akamai** [comment]
@mzimry Thanks for the report! 

Has this bug been occurring consistently for you or does it seem to just be a one-off issue?
