### ISSUE TITLE
[Bug]: Crash when running linode-cli domains records-list --help

### ISSUE THREAD

**Issue by diazona** [linode/linode-cli#581]
### CLI Version

linode-cli 5.48.2 Built off spec version 4.171.0

### Command

```
linode-cli domains records-list --help
```

### Output

```
linode-cli domains records-list [DOMAINID]
Domain Records List
API Documentation: https://www.linode.com/docs/api/domains/#domain-records-list

Example Usage: 
  linode-cli domains records-list 1234

Arguments:
Traceback (most recent call last):
  File "/home/diazona/.local/bin/linode-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/diazona/.local/pipx/venvs/linode-cli/lib/python3.12/site-packages/linodecli/__init__.py", line 260, in main
    action_help(cli, parsed.command, parsed.action)
  File "/home/diazona/.local/pipx/venvs/linode-cli/lib/python3.12/site-packages/linodecli/arg_helpers.py", line 401, in action_help
    nullable_fmt = " (nullable)" if arg.nullable else ""
                                    ^^^^^^^^^^^^
AttributeError: 'OpenAPIResponseAttr' object has no attribute 'nullable'
```

### Expected Behavior

The command should have printed a help message describing the usage and arguments of `linode-cli domains records-list`.

### Actual Behavior

The command raised an exception and did not print information about the arguments..

### Steps to Reproduce

1. Install `linode-cli` (I used `pipx` on Python 3.11 and again on 3.12 but I expect that any standard method of installing it would give the same result)
2. Run `linode-cli domains records-list --help`

**Comment by lgarber-akamai** [comment]
@diazona Thank you for the report! The fix for this issue has been merged and will be available in the next release.

**Comment by diazona** [comment]
Fantastic, thank you for the fix!
