### ISSUE TITLE
"Image is not valid" when creating Linode from backup

### ISSUE THREAD

**Issue by emilv** [linode/linode-cli#61]
I try to create a Linode with the following command:

    linode-cli linodes create --type g6-standard-4 --region eu-central --backup_id 103216265 --backups_enabled false --private_ip true --group SmoothcompNew

Result:

```
Request failed: 400
┌errors─┬────────────────────┐
│ field │ reason             │
├───────┼────────────────────┤
│ image │ image is not valid │
└───────┴────────────────────┘
```

I have verified that the backup is in the same region. It does not matter whether the backup is a manual or automatic snapshot.

**Comment by Dorthu** [comment]
Can you try running the same command with `--no-defaults`?  We've had a couple other issues reported that boiled down to unintuitive behavior with the selected default region/image/type from the configuration, I'm thinking this is likely a similar problem.

**Comment by emilv** [comment]
`--no-defaults` works

**Comment by LBGarber** [comment]
Closing as this issue seems to be resolved in my testing. Feel free to reply if this issue is still occurring.
