### ISSUE TITLE
[Feature]: support enabling/disabling watchdog/lassie

### ISSUE THREAD

**Issue by jschauma** [linode/linode-cli#645]
### Description

The API supports setting `watchdog_enable` to `true` or `false` via `curl`:
https://techdocs.akamai.com/linode-api/reference/put-linode-instance

But it seems there's no command-line option for `linode-cli` to do the same.

It'd be great to have that option added.

### Potential Usage Example

linode-cli linodes config-watchdog --enable
linode-cli linodes config-watchdog --disable

**Comment by dwfreed** [comment]
I think what you're looking for is `linode-cli linodes update <LinodeID> --watchdog_enable false`; eg, if your Linode ID is 1234, `linode-cli linodes update 1234 --watchdog_enable false` will disable Lassie, and replace `false` with `true` to enable it.

**Comment by jschauma** [comment]
Oh, nice - totally missed that option!  Right on, thanks!
