### ISSUE TITLE
Use $XDG_CONFIG_HOME for config files

### ISSUE THREAD

**Issue by tarqd** [linode/linode-cli#77]
I think it'd be better if `linode-cli` respected the `$XDG_CONFIG_HOME ` variable and defaulted to `$HOME/.config/linode-cli` as the config dir if it's not set.

Personally, I don't like my home directory getting cluttered and this variable seems to be the standard for newer software unix-y systems. 

Related package: https://pypi.org/project/xdg/

It's fairly small, just checks the env variables and has sane defaults if the variables are not set.

Reference: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by lgarber-akamai** [comment]
Closing since the relevant PR has already been merged.
