### ISSUE TITLE
k8s-alpha create does not honor --node-type and --master-type set during configure

### ISSUE THREAD

**Issue by kengu** [linode/linode-cli#93]
During `linode-cli configure`, I set the default values for `--node-type` and `--master-type` to `g6-standard-2`. 

However, I still got `g6-standard-4` when not supplying `--node-type` and `--master-type` to `linode-cli k8s-alpha create ...`.

**Comment by asauber** [comment]
Right, k8s-alpha currently does not use the global configuration for node type hints, because k8s masters require at least 2 CPUs. Some logic could be added to make this work (with a minimum number of cores for masters).
