### ISSUE TITLE
Warning given to update, but upgrade command doesn't fix it

### ISSUE THREAD

**Issue by GemmaLamont** [linode/linode-cli#98]
When running simple commands I get 

"The API responded with version 4.0.15, which is newer than the CLI's version of 4.0.11.  Please update the CLI to get access to the newest features.  You can update with a simple `pip install --upgrade linode-cli`"

However, running `pip install --upgrade linode-cli` says I am already up to date.

**Comment by Dorthu** [comment]
Sorry for the inconvenience!  I've updated the Linode CLI package, a `pip install --upgrade linode-cli` should now pull down version `2.0.20` which should fix the warning.  You can also use `--suppress-warnings` to prevent warnings from being outputted in all cases.
